name: afghan_deals_pro
description: Afghan Deals Pro - The trusted community of buyers and sellers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.8.0

  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Backend
  supabase_flutter: ^2.3.0



  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # Auth
  google_sign_in: ^6.2.1

  # Media
  image_picker: ^1.1.2

  # Push Notifications
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.2.2

  # Storage
  shared_preferences: ^2.2.3

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-01.png"
  min_sdk_android: 21
  web:
    generate: false

flutter_native_splash:
  color: "#84D2FF"
  color_dark: "#84D2FF"
  android_12:
    color: "#84D2FF"
    icon_background_color: "#84D2FF"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/flags/
    - assets/images/dummy_cars/
    - assets/images/calendar_icon.svg
    - assets/images/car_filter_icons/
    - assets/icons/
    - assets/icons/mobile_filter/
    - assets/icons/electronics/
    - assets/icons/furniture/
